### ISSUE TITLE
Update explainers to reflect latest discussions

### ISSUE THREAD

**Issue by addyosmani** [WICG/priority-hints#14]
Trying to summarize a few discussions before filing PRs:

1. We are now going to use the `importance` attribute instead of `group`. Related to #6 
2. We will use the following importance buckets: `critical`, `high`, `medium`, `low`, `unimportant` #7 
3. We do want a JS equivalent for what we're doing here, but have not concretely explored this yet. #11 touches on this. We can say "There is a desire to explore priority hints `importance` in terms of fetch.". Perhaps we should just reference that issue or another to encourage continuing that discussion.
4. V0 will not explore a resource throttling algorithm, which came up in https://github.com/WICG/priority-hints/issues/10. Does that sound reasonable? We've had some input on this topic but unsure if enough to make a call here.

**Comment by yoavweiss** [comment]
Thanks for summarizing the different discussions! This all makes sense to me.
Regarding 4), UAs could apply throttling on low priority third parties in H2 regardless of explicit hints. It's also something we can explore using SW.

**Comment by addyosmani** [comment]
> Thanks for summarizing the different discussions! 

Cheers!

> 4), UAs could apply throttling on low priority third parties in H2 regardless of explicit hints. It's also something we can explore using SW.

This is a useful reminder and something good to be aware of.
