### ISSUE TITLE
Link header support

### ISSUE THREAD

**Issue by addyosmani** [WICG/priority-hints#21]
After speaking to Kenji about the syntax for Link header support, he was proposing we add a mention for:

```
Link: <https://example.com/images/hero.jpg>; rel=preload; as=image; importance=high
```

**Comment by domfarolino** [comment]
So essentially just adding `importance=$value` right? Looks good to me. I can submit a PR to the doc if wanted.

**Comment by addyosmani** [comment]
Go for it! PRs welcome. We can iterate as needed on the shape of Link header support in there. Just merged your first set of clean-ups.
