### ISSUE TITLE
Add a bit about the developer tools

### ISSUE THREAD

**Issue by domfarolino** [WICG/priority-hints#25]
The developer tools aren't standard, but we should probably mention as a *note* somewhere mentioning:

> *It is encouraged that a browser's developer tools, where possible, communicate the effect of an importance attribute on the computed priority of a resource as network information*

Again, it's far from mandatory, but seems worth throwing in since it's something most browsers can do and might make DX a little better?

**Comment by addyosmani** [comment]
I agree that some advisoral text on the debugging workflow would be useful. I would be interested in checking if other specs have attempted to capture the developer tooling side of things that we can use as a frame for how best to note this.

**Comment by domfarolino** [comment]
The closest thing *I personally* can think of are small [subsections](https://console.spec.whatwg.org/#loglevel-severity) in the Console Standard; because it is fairly closely related to the DevTools, there a few non-normative examples of how current implementations do things. This is not super-related to this but hope it *might* help a little?

**Comment by addyosmani** [comment]
I consulted with Yoav regarding the Priority Hints debugging story a few days ago and he noted that although it's fine for us to capture some notes on this topic in the explainer (or another readme in the repo), we should probably hold-off on discussing developer tooling in the main spec text. Does that sound reasonable?

Perhaps we should introduce a DEBUGGING.md markdown file or similar?

**Comment by domfarolino** [comment]
Looks like this slipped to the bottom of my inbox completely unbeknownst to me. I think a `DEBUGGING.md` sounds good with perhaps some thoughts that we've been throwing around about UI stuff. It can probably be on the backlog too as it seems fairly low-priority (no pun intended) at this point.

**Comment by pmeenan** [comment]
Closing this out as the changes have been merged into fetch which is where the request priority is exposed (and this will largely go away when the remaining changes are merged into HTML).  There are MDN docs for the attributes and behaviors but anything beyond that is likely to be browser-specific and should probably be covered in blog posts, documts and tooling that discuss it for the given browser.
