### ISSUE TITLE
Update EXAMPLES.md and EXPLAINER.md to reflect spec

### ISSUE THREAD

**Issue by coliff** [WICG/priority-hints#28]
The Examples file mentions `importance=critical` and `importance=medium` but the proposed spec (https://wicg.github.io/priority-hints/) only mentions setting importance with either high or low.

Should `EXAMPLES.md` be updated to reflect the latest spec?

**Comment by domfarolino** [comment]
Yes it probably should. At this point we're in the process of testing an experimental implementation and iterating on it trying to find some solid use-cases that we might be able to show developers to get a better loading experience, so I imagine once we nail a few solid cases down the document will be updated with much newer things.

Not sure if there might be a plan on moving the contents to a section in the explainer spec itself though too...

**Comment by addyosmani** [comment]
I think we should focus on the explainer being the canonical source for examples and can refactor our snippets to ensure they're using the latest values of `low`, `high` or auto. 

> Not sure if there might be a plan on moving the contents to a section in the explainer spec itself though too...

Let's do it. When we update the examples we can also drop EXAMPLES.md and reference explainer text for them instead.

**Comment by domfarolino** [comment]
I believe EXPLAINER.md is also a little out-of-date too. Wrapping that issue in into this one by changing the title.
