### ISSUE TITLE
Document "safety" of applying priority hints

### ISSUE THREAD

**Issue by addyosmani** [WICG/priority-hints#29]
After chatting with @domfarolino today, an item we noted would be useful for the explainer is the safety of using priority hints. 

* Hints should be safe in that hints specified by a site shouldn't degrade performance both (1) in a browser that supports `importance` and (2) in a browser that does not. 
* UAs should feel free to apply other heuristics in addition to hints to decide on how they load content. e.g in Chrome, with hero images Chrome may automatically detect the image is important if it gets to layout early enough but all browsers would benefit from knowing which images you want loaded "earlier" and which are safe to load "later", regardless of how they use this information.
* This same logic applies for scripts. Browsers may have different heuristics that work differently across browsers for scripts (e.g with async, defer etc) but a site could fix any mis-guesses across the board by being explicit using hints. Applying hints shouldn't negatively impact the overall experience.

**Comment by domfarolino** [comment]
This _might_ be able to be closed given the most recent PR merge, but not 100% sure so I'll leave it up to you.
