### ISSUE TITLE
add use case for service worker resource installation

### ISSUE THREAD

**Issue by wanderview** [WICG/priority-hints#40]
Another use case for priority hints I've heard recently is to de-prioritize `fetch()` and `cache.addAll()` calls in a service worker install event.  This could help avoid the background installation of many resources from starving out any requests initiated from the active window on the main thread.

Just FYI in case this is worth including in the list of use cases in the spec.

**Comment by nolanlawson** [comment]
Thanks for filing this issue; I was just about to do that. :)

I opened [an issue on Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1531511) before realizing that there is no guarantee that resources requested during the Service Worker install phase (e.g. `caches.addAll()`) are lower-priority than requests made on the main thread. So it looks like ideally we would want priority hints for `cache[s].add[All]` as well.

**Comment by wanderview** [comment]
`cache.addAll()` takes Request objects, so it should accept the `importance` attribute just like fetch.

**Comment by pmeenan** [comment]
There are now specs and examples for how it is exposed on the Request object and used with fetch(). It will work with cache[s].add[All] as well but there aren't any explicit examples of that.
