### ISSUE TITLE
Bring back examples into the explainer

### ISSUE THREAD

**Issue by yoavweiss** [WICG/priority-hints#41]
While answering questions on the [TAG review](https://github.com/w3ctag/design-reviews/issues/241#issuecomment-474800105), it seemed like the usage examples have moved from the explainer to the spec itself. While it's important to have them in the spec, it seems equally important to have them as part of the explainer. We should probably copy them back.

**Comment by addyosmani** [comment]
@yoavweiss would a 1:1 copy of them back to the explainer suffice? Happy to PR in this change. Should be minimal effort.

**Comment by yoavweiss** [comment]
Yeah, a 1:1 copy would be sufficient
