### ISSUE TITLE
Archive this?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/priority-hints#43]
Given https://github.com/whatwg/html/issues/3670#issuecomment-568765838 ... should we archive this incubation?

**Comment by domfarolino** [comment]
Not sure. I closed the HTML Standard issue mostly because it was not actionable, but I think as we (Chrome) continue to explore our implementation, this is still a reasonable place to store experimental findings and spec adjustments, before bringing to an appropriate venue like WHATWG.

**Comment by marcoscaceres** [comment]
Sounds good. Thanks for the update!

**Comment by jeffreytgilbert** [comment]
My biggest suggestion to this proposal is that if it does end up resurfacing and moving forward, the default behavior should not attempt to change the order in which resources are fetched. Attempting to measure falloff of requests when the load order is shuffled around based on browser inferred and assumed priority made for painful days chasing what was going on there. I'm all for explicit indication that things can be intelligently shuffled, but just want to pump the brakes on automagically doing it for the web as a whole.
