### ISSUE TITLE
Mobile browser support

### ISSUE THREAD

**Issue by mziemer21** [WICG/priority-hints#45]
Is this available for origin trial in Chrome for Android? If so, which version started supporting it? I can't find a support gird anywhere.

**Comment by domfarolino** [comment]
Chrome ran an origin trial, but we're currently putting the implementation (and origin trials) on-hold, since we'll need to make some changes to make it more effective

**Comment by mziemer21** [comment]
Thanks for the update. Will this repo be updated once the changes are ready?

**Comment by domfarolino** [comment]
It should be, yes. I'll close this for now, and if we're able to move forward with this proposal, feel free to watch the repo and you'll be notified of any changes.
