### ISSUE TITLE
Responsive Image Support?

### ISSUE THREAD

**Issue by pmeenan** [WICG/priority-hints#46]
`importance` is currently spec'd to apply to the <img> element but it's an all-or-nothing approach.  If a design has an image in the viewport for desktop but is hidden in mobile layouts then a site needs to make a judgement call on if it wants to always boost the priority or not.

I've never used it that way (and haven't yet verified that it works in Chrome or other browsers) but it appears that preload supports the media attribute which should allow for boosting the importance of an image explicitly with a media query (just requires preloading the image and can't be scoped on the image tag itself.

If this is the way we want to recommend people use priority hints (and preload in general) with responsive designs, it is probably worth having an example demonstrating it and making it clear.

**Comment by yoavweiss** [comment]
Interesting!



> I've never used it that way (and haven't yet verified that it works in Chrome or other browsers)

Should work in both [Chromium](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/loader/preload_helper.cc;l=291?q=preloadIfNeeded&ss=chromium) and [WebKit](https://github.com/WebKit/WebKit/blob/e98ff129bc8eba06ac17105f19c5f0e142aab853/Source/WebCore/loader/LinkLoader.cpp#L257). Not sure about Firefox.



> If this is the way we want to recommend people use priority hints (and preload in general) with responsive designs, it is probably worth having an example demonstrating it and making it clear.

Makes sense to add an example, but would similarly make sense to define importance on the different `<source>`s as overriding the one on `<img>`. It'd require a bit more work on the spec side, but would be easier for developers, assuming that this is something people want to do.

**Comment by pmeenan** [comment]
Going to close this. For the purposes of importance, responsive can be handled with ```preload``` for any individual sources where the ```<img>``` importance needs to be overridden since ```<link rel=preload>``` supports media queries.

That also handles srcset and sizes which is broader than just ```<picture>``` support.
