### ISSUE TITLE
Processing model

### ISSUE THREAD

**Issue by martinthomson** [WICG/priority-hints#52]
These are notably absent.

The intent might be inferred from the supporting text, but it would be good to have it in writing.  

I assume that the only specified processing here would relate to the way that the provided "importance" value is taken and carried along with associated fetches.  That is, the browser will take the value and hold it until it needs to make a prioritization decision, whereupon it can "use" the value in some unspecified way.

**Comment by pmeenan** [comment]
Yep, sorry - was planning on taking a pass at them this week.  Functionally there's not a lot to the actual processing model, it's just the mechanics for translating the DOM string into the fetch enum and carrying the importance through to fetch (and how it passes through to service workers). Once within fetch it goes into a black hole for the browser to use internally as it sees fit and that part intentionally won't be specified.

**Comment by pmeenan** [comment]
The processing model monkeypatches to HTML and fetch are all in place now.
