### ISSUE TITLE
Priority is not magic

### ISSUE THREAD

**Issue by martinthomson** [WICG/priority-hints#55]
Specifications like this need very careful disclaimers.

An important disclaimer here is that priority is something of a zero-sum game.  Marking everything as high priority is likely to make performance worse overall.  That is, priority is about moving one thing out of the way for another.

This might seem like an obvious thing, but I've heard enough stories to know that people are prone to the sort of magical thinking that leads to slapping `importance="high"` on every load.

**Comment by pmeenan** [comment]
Good point, thanks. Preload and HTTP/2 push both got burned by that where people when ahead and just sent everything. I'll add some strong language to the intro of both the spec and explainer.

**Comment by HolgerJeromin** [comment]
Can this issue be closed?
